### ISSUE TITLE
Create library for fault injection

### ISSUE THREAD

**Issue by csw** [csw/crdt-flix#4]
Start by simulating network errors, randomly choosing whether to actually perform the operation or not (to simulate a network error before or after the request is transmitted), and retrying after a delay.

Also: partitions, maybe duplicate messages?

**Comment by salessa** [comment]
Planned Design(please comment)

An external python module will be used to simulate failures. The python module will have the service availability value and the min and max network delay as a configuration parameter. The clients will utilize the module as follows:
1. Before sending requests to the server, the client(written in Erlang) will send a request to the python module(isAlive request). The module will return a boolean value indicating if the server is currently "up" or "down".
2. if the module indicates the server is "up", the client will send it's request to the server.
3. the fault injection module can be used to introduce to delays as well. This can be simply be done by delaying it's response to isAlive requests.

We can add more features as times goes on.
